### ISSUE TITLE
How I can add a new language?

### ISSUE THREAD

**Issue by MichaeINeumann** [Cobinja/CobiSymbolOutline#5]
Hi, I need support for the KRL "KUKA ROBOT LANGUAGE".
Datei - ending .src

Funktion
DEF *()
GLOBAL DEF *( )
DEFFCT * * (*:IN, *:IN,  *:IN)
GLOBAL DEFFCT BOOL even_number (n1: IN)

How can I set in the settings. 
Maybe you can explain me, how I can Change. So I can do it in a Fork.

**Comment by Cobinja** [comment]
This extension does not provide language support, but uses the symbols provided by Visual Studio Code, which in turn needs another extension to support specific languages.
If the language's symbols work in the builtin symbol outline, they should work in this extension as well.
